name: Build Java JAR

on: [workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init

    - name: Install JDK
      run: sudo apt install default-jdk

    - name: Build
      run: ./build.sh host-jar "release"

    - uses: actions/upload-artifact@v2
      with:
        path: dist

  build-windows:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init

    - name: Build
      run: . .\build.ps1; Build-Library -BuildType "Release" -Arch "x64" -LangBinding "Java"

    - uses: actions/upload-artifact@v2
      with:
        path: dist
